package com.example.util

object LocalizationHelper {
    private val translations = mapOf(
        "ar" to mapOf(
            "home" to "الرئيسية",
            "live_tv" to "القنوات المباشرة",
            "movies" to "الأفلام",
            "series" to "المسلسلات",
            "favorites" to "المفضلة",
            "my_account" to "حسابي",
            "continue_watching" to "متابعة المشاهدة",
            "all" to "الكل",
            "search_hint" to "البحث عن فيلم، مسلسل، قناة...",
            "settings_title" to "إعدادات التطبيق",
            "app_language" to "لغة التطبيق",
            "video_player" to "مشغل الفيديو",
            "accent_color" to "اللون الأساسي للواجهة",
            "stream_quality" to "جودة البث الافتراضية",
            "clear_cache" to "مسح الذاكرة المؤقتة",
            "clear_cache_desc" to "يساعد في تسريع التطبيق وحل مشكلات التقطيع",
            "cache_cleared" to "تم مسح الذاكرة المؤقتة بنجاح! 🎉",
            "server_status" to "حالة السيرفر",
            "playlists" to "الاشتراكات والاشتراك النشط",
            "theme" to "مظهر التطبيق",
            "vlc_desc" to "يتطلب تثبيت تطبيق VLC الخارجي",
            "mx_desc" to "يتطلب تثبيت تطبيق MX Player الخارجي",
            "system_desc" to "تشغيل بمشغل النظام الافتراضي",
            "exoplayer_desc" to "المشغل الداخلي السريع والمستقر",
            "server" to "السيرفر النشط",
            "no_history" to "لا يوجد تاريخ مشاهدة بعد",
            "favorite_added" to "تمت الإضافة للمفضلة",
            "favorite_removed" to "تمت الإزالة من المفضلة",
            "save" to "حفظ",
            "cancel" to "إلغاء",
            "close" to "إغلاق",
            "change_lang_alert" to "تغيير اللغة يتطلب إعادة تشغيل التطبيق لتطبيق كافة التغييرات.",
            "auto" to "تلقائي (Auto)",
            "fhd" to "عالية (FHD 1080p)",
            "hd" to "متوسطة (HD 720p)",
            "sd" to "منخفضة (SD 480p)",
            "legal" to "قانوني",
            "terms_conditions" to "الشروط والأحكام",
            "privacy_policy" to "سياسة الخصوصية"
        ),
        "en" to mapOf(
            "home" to "Home",
            "live_tv" to "Live TV",
            "movies" to "Movies",
            "series" to "Series",
            "favorites" to "Favorites",
            "my_account" to "Account",
            "continue_watching" to "Continue Watching",
            "all" to "All",
            "search_hint" to "Search movies, series, channels...",
            "settings_title" to "App Settings",
            "app_language" to "App Language",
            "video_player" to "Video Player",
            "accent_color" to "Theme Accent Color",
            "stream_quality" to "Default Stream Quality",
            "clear_cache" to "Clear Cache",
            "clear_cache_desc" to "Helps speed up the app and solve stuttering issues",
            "cache_cleared" to "Cache cleared successfully! 🎉",
            "server_status" to "Server Status",
            "playlists" to "Active Subscriptions",
            "theme" to "App Theme",
            "vlc_desc" to "Requires external VLC Player app installed",
            "mx_desc" to "Requires external MX Player app installed",
            "system_desc" to "Play using default System Player",
            "exoplayer_desc" to "Fast & stable built-in player",
            "server" to "Active Server",
            "no_history" to "No watch history yet",
            "favorite_added" to "Added to Favorites",
            "favorite_removed" to "Removed from Favorites",
            "save" to "Save",
            "cancel" to "Cancel",
            "close" to "Close",
            "change_lang_alert" to "Changing language might require restarting the app for complete changes.",
            "auto" to "Automatic (Auto)",
            "fhd" to "High (FHD 1080p)",
            "hd" to "Medium (HD 720p)",
            "sd" to "Low (SD 480p)",
            "legal" to "Legal",
            "terms_conditions" to "Terms and Conditions",
            "privacy_policy" to "Privacy Policy"
        ),
        "fr" to mapOf(
            "home" to "Accueil",
            "live_tv" to "TV en Direct",
            "movies" to "Films",
            "series" to "Séries",
            "favorites" to "Favoris",
            "my_account" to "Mon Compte",
            "continue_watching" to "Continuer à regarder",
            "all" to "Tout",
            "search_hint" to "Rechercher des films, séries, chaînes...",
            "settings_title" to "Paramètres",
            "app_language" to "Langue de l'application",
            "video_player" to "Lecteur Vidéo",
            "accent_color" to "Couleur d'accentuation",
            "stream_quality" to "Qualité de flux par défaut",
            "clear_cache" to "Vider le cache",
            "clear_cache_desc" to "Aide à accélérer l'application et à résoudre les saccades",
            "cache_cleared" to "Cache vidé avec succès! 🎉",
            "server_status" to "Statut du Serveur",
            "playlists" to "Abonnements Actifs",
            "theme" to "Thème de l'application",
            "vlc_desc" to "Nécessite l'application externe VLC Player",
            "mx_desc" to "Nécessite l'application externe MX Player",
            "system_desc" to "Jouer avec le lecteur système par défaut",
            "exoplayer_desc" to "Lecteur interne rapide et stable",
            "server" to "Serveur Actif",
            "no_history" to "Aucun historique de visionnage",
            "favorite_added" to "Ajouté aux Favoris",
            "favorite_removed" to "Retiré des Favoris",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "close" to "Fermer",
            "change_lang_alert" to "Changer de langue peut nécessiter le redémarrage de l'application.",
            "auto" to "Automatique (Auto)",
            "fhd" to "Élevée (FHD 1080p)",
            "hd" to "Moyenne (HD 720p)",
            "sd" to "Basse (SD 480p)",
            "legal" to "Mentions légales",
            "terms_conditions" to "Conditions Générales",
            "privacy_policy" to "Politique de Confidentialité"
        )
    )

    fun translate(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["ar"]?.get(key) ?: key
    }
}
